services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example

  redis:
    image: docker.io/bitnami/redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - '6380:6379'
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
  
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8092:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8093:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret

  # nms:
  #   image: skyface753/nms
  #   ports:
  #     - 8001:8000
  #     - 1936:1935
  #   environment:
  #     - ALLOW_ORIGIN=*

   